/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdhkarRouteImport } from './routes/_authenticated/adhkar'
import { Route as AuthenticatedGardenRouteImport } from './routes/_authenticated/garden'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPathRouteImport } from './routes/_authenticated/path'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedLessonLessonIdRouteImport } from './routes/_authenticated/lesson.$lessonId'
import { Route as AuthenticatedReadIndexRouteImport } from './routes/_authenticated/read.index'
import { Route as AuthenticatedReadSurahIdRouteImport } from './routes/_authenticated/read.$surahId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdhkarRoute = AuthenticatedAdhkarRouteImport.update({
  id: '/adhkar',
  path: '/adhkar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGardenRoute = AuthenticatedGardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPathRoute = AuthenticatedPathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLessonLessonIdRoute =
  AuthenticatedLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReadIndexRoute = AuthenticatedReadIndexRouteImport.update({
  id: '/read/',
  path: '/read/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReadSurahIdRoute =
  AuthenticatedReadSurahIdRouteImport.update({
    id: '/read/$surahId',
    path: '/read/$surahId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/adhkar': typeof AuthenticatedAdhkarRoute
  '/garden': typeof AuthenticatedGardenRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/path': typeof AuthenticatedPathRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
  '/read/$surahId': typeof AuthenticatedReadSurahIdRoute
  '/read/': typeof AuthenticatedReadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/adhkar': typeof AuthenticatedAdhkarRoute
  '/garden': typeof AuthenticatedGardenRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/path': typeof AuthenticatedPathRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
  '/read/$surahId': typeof AuthenticatedReadSurahIdRoute
  '/read': typeof AuthenticatedReadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/adhkar': typeof AuthenticatedAdhkarRoute
  '/_authenticated/garden': typeof AuthenticatedGardenRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/path': typeof AuthenticatedPathRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
  '/_authenticated/read/$surahId': typeof AuthenticatedReadSurahIdRoute
  '/_authenticated/read/': typeof AuthenticatedReadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/adhkar'
    | '/garden'
    | '/onboarding'
    | '/path'
    | '/settings'
    | '/today'
    | '/lesson/$lessonId'
    | '/read/$surahId'
    | '/read/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/adhkar'
    | '/garden'
    | '/onboarding'
    | '/path'
    | '/settings'
    | '/today'
    | '/lesson/$lessonId'
    | '/read/$surahId'
    | '/read'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/adhkar'
    | '/_authenticated/garden'
    | '/_authenticated/onboarding'
    | '/_authenticated/path'
    | '/_authenticated/settings'
    | '/_authenticated/today'
    | '/_authenticated/lesson/$lessonId'
    | '/_authenticated/read/$surahId'
    | '/_authenticated/read/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/adhkar': {
      id: '/_authenticated/adhkar'
      path: '/adhkar'
      fullPath: '/adhkar'
      preLoaderRoute: typeof AuthenticatedAdhkarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/garden': {
      id: '/_authenticated/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof AuthenticatedGardenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/path': {
      id: '/_authenticated/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof AuthenticatedPathRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lesson/$lessonId': {
      id: '/_authenticated/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/read/': {
      id: '/_authenticated/read/'
      path: '/read'
      fullPath: '/read/'
      preLoaderRoute: typeof AuthenticatedReadIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/read/$surahId': {
      id: '/_authenticated/read/$surahId'
      path: '/read/$surahId'
      fullPath: '/read/$surahId'
      preLoaderRoute: typeof AuthenticatedReadSurahIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdhkarRoute: typeof AuthenticatedAdhkarRoute
  AuthenticatedGardenRoute: typeof AuthenticatedGardenRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPathRoute: typeof AuthenticatedPathRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedLessonLessonIdRoute: typeof AuthenticatedLessonLessonIdRoute
  AuthenticatedReadSurahIdRoute: typeof AuthenticatedReadSurahIdRoute
  AuthenticatedReadIndexRoute: typeof AuthenticatedReadIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdhkarRoute: AuthenticatedAdhkarRoute,
  AuthenticatedGardenRoute: AuthenticatedGardenRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPathRoute: AuthenticatedPathRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedLessonLessonIdRoute: AuthenticatedLessonLessonIdRoute,
  AuthenticatedReadSurahIdRoute: AuthenticatedReadSurahIdRoute,
  AuthenticatedReadIndexRoute: AuthenticatedReadIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
